# Generated by Django 5.1.5 on 2025-02-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Camino', max_length=255, verbose_name='Nombre de la categoria')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons_category/', verbose_name='Icono de la categoria')),
                ('color', models.CharField(default='', max_length=255, verbose_name='Color de la categoria')),
                ('context', models.CharField(choices=[('nodos', 'Nodos'), ('objetos_czml', 'Objetos_Czml'), ('salones', 'Salones'), ('usuarios', 'Usuarios'), ('horarios', 'Horarios')], default='nodos', max_length=255, verbose_name='Contexto')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del punto')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('altitude', models.FloatField(default=0, verbose_name='Altitud')),
                ('category_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_node', to='czml.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='Distancia')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='czml.node', verbose_name='Nodo final')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='czml.node', verbose_name='Nodo inicial')),
            ],
            options={
                'verbose_name': 'Arista',
                'verbose_name_plural': 'Aristas',
                'db_table': 'edges',
            },
        ),
        migrations.CreateModel(
            name='CzmlObject',
            fields=[
                ('id_object', models.CharField(default='0000', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del objeto CZML')),
                ('type_object', models.CharField(default='Modelo', max_length=100, verbose_name='Tipo de objeto')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Activado')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_czml', to='czml.node', verbose_name='Ubicacion')),
            ],
            options={
                'verbose_name': 'Objeto CZML',
                'verbose_name_plural': 'Objetos CZML',
                'db_table': 'czml_objects',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(verbose_name='Distancia total')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_routes', to='czml.node', verbose_name='Nodo de destino')),
                ('path', models.ManyToManyField(related_name='path_nodes', to='czml.node', verbose_name='Secuencia de nodos')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_routes', to='czml.node', verbose_name='Nodo de inicio')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'db_table': 'routes',
            },
        ),
    ]
