# Generated by Django 5.1.5 on 2025-02-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
