# Generated by Django 5.1.5 on 2025-02-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0002_remove_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='czmlobject',
            name='heading',
            field=models.FloatField(default=0.0, verbose_name='Rotación Y'),
        ),
        migrations.AddField(
            model_name='czmlobject',
            name='pitch',
            field=models.FloatField(default=0.0, verbose_name='Rotacion X'),
        ),
        migrations.AddField(
            model_name='czmlobject',
            name='roll',
            field=models.FloatField(default=0.0, verbose_name='Rotacion Z'),
        ),
    ]
