# Generated by Django 5.1.5 on 2025-02-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0003_czmlobject_heading_czmlobject_pitch_czmlobject_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='czmlobject',
            name='scale',
            field=models.FloatField(default=1, verbose_name='Escala'),
        ),
    ]
