# Generated by Django 5.1.5 on 2025-03-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0004_czmlobject_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Orden del nodo en la ruta')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czml.node', verbose_name='Nodo de la ruta')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='czml.route', verbose_name='Ruta a la que pertenence')),
            ],
            options={
                'verbose_name': 'Nodo de la ruta',
                'verbose_name_plural': 'Nodos de la ruta',
                'db_table': 'route_nodes',
            },
        ),
        migrations.AlterField(
            model_name='route',
            name='path',
            field=models.ManyToManyField(related_name='path_nodes', to='czml.routenode', verbose_name='Secuencia de nodos'),
        ),
    ]
