# Generated by Django 5.1.5 on 2025-03-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0005_routenode_alter_route_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='path',
        ),
    ]
