# Generated by Django 5.1.5 on 2025-03-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0006_remove_route_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='czmlobject',
            name='category_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_object', to='czml.category', verbose_name='Categoria del objeto'),
        ),
        migrations.AddField(
            model_name='czmlobject',
            name='image_object',
            field=models.ImageField(blank=True, null=True, upload_to='images_czml/', verbose_name='Imagen del objeto'),
        ),
    ]
