# Generated by Django 5.1.5 on 2025-04-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0007_czmlobject_category_object_czmlobject_image_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='context',
            field=models.CharField(choices=[('nodos', 'Nodos'), ('objetos_czml', 'Objetos_Czml'), ('salones', 'Salones'), ('usuarios', 'Usuarios'), ('horarios', 'Horarios'), ('recursos', 'Recursos')], default='nodos', max_length=255, verbose_name='Contexto'),
        ),
    ]
