# Generated by Django 5.1.5 on 2025-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0008_alter_category_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='czmlobject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del objeto'),
        ),
    ]
