# Generated by Django 5.1.5 on 2025-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0009_czmlobject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='czmlobject',
            name='name_presentation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la presentacion'),
        ),
    ]
