# Generated by Django 5.1.5 on 2025-03-26 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('czml', '0007_czmlobject_category_object_czmlobject_image_object'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la carrera')),
                ('code', models.CharField(max_length=20, verbose_name='Código de la carrera')),
                ('duration', models.IntegerField(verbose_name='Duración de la carrera')),
                ('snies_code', models.CharField(max_length=20, verbose_name='Código SNIES')),
                ('url_webpage', models.URLField(blank=True, default='', null=True, verbose_name='Página web')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del curso')),
                ('code', models.CharField(max_length=20, verbose_name='Código del curso')),
                ('semester', models.IntegerField(verbose_name='Semestre')),
                ('credits', models.IntegerField(verbose_name='Créditos del curso')),
                ('teacher', models.CharField(max_length=255, verbose_name='Profesor')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='universidad.career', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Course_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(verbose_name='Grupo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='universidad.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_course', to=settings.AUTH_USER_MODEL, verbose_name='Miembro')),
            ],
            options={
                'verbose_name': 'Curso de usuario',
                'verbose_name_plural': 'Cursos de usuario',
                'db_table': 'courses_users',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la facultad')),
                ('dean', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decano')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_faculty', to='czml.node', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'faculties',
            },
        ),
        migrations.AddField(
            model_name='career',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='universidad.faculty', verbose_name='Facultad'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del recurso')),
                ('state', models.CharField(default='Funcional', max_length=255, verbose_name='Estado')),
                ('reference', models.CharField(max_length=255, verbose_name='Referencia')),
                ('type_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_resourse', to='czml.category', verbose_name='Tipo de recurso')),
            ],
            options={
                'verbose_name': 'Recurso universitario',
                'verbose_name_plural': 'Recursos universitarios',
                'db_table': 'university_resources',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('day_of_week', models.CharField(max_length=10, verbose_name='Día de la semana')),
                ('category_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_schedule', to='czml.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Horario de estudio',
                'verbose_name_plural': 'Horarios de estudio',
                'db_table': 'study_schedules',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del aula')),
                ('availability', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('area', models.FloatField(verbose_name='Area')),
                ('floor', models.IntegerField(verbose_name='Piso')),
                ('object_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_father', to='czml.czmlobject', verbose_name='Edificio')),
                ('resources', models.ManyToManyField(related_name='resources', to='universidad.resource', verbose_name='Recursos')),
                ('type_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_room', to='czml.category', verbose_name='Tipo de aula')),
                ('schedule', models.ManyToManyField(related_name='schedule_availability', to='universidad.schedule', verbose_name='Horarios')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='Schedule',
            field=models.ManyToManyField(related_name='schedule_course', to='universidad.schedule', verbose_name='Horario'),
        ),
    ]
