# Generated by Django 5.1.5 on 2025-04-05 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czml', '0008_alter_category_context'),
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_room', to='czml.node', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Piso'),
        ),
    ]
