# Generated by Django 5.1.5 on 2025-04-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0002_room_location_alter_room_area_alter_room_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, related_name='resources', to='universidad.resource', verbose_name='Recursos'),
        ),
    ]
