# Generated by Django 5.1.5 on 2025-04-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0003_alter_room_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resources',
            field=models.ManyToManyField(related_name='resources', to='universidad.resource', verbose_name='Recursos'),
        ),
    ]
