# Generated by Django 5.1.5 on 2025-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0004_alter_room_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Capacidad'),
        ),
    ]
