# Generated by Django 5.1.5 on 2025-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0005_alter_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_room',
            field=models.ImageField(blank=True, null=True, upload_to='images_rooms/', verbose_name='Imagen del aula'),
        ),
    ]
