# Generated by Django 5.1.5 on 2025-04-19 14:56

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0006_room_image_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='interfaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la interfaz')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images_logo/', verbose_name='Logo')),
                ('name_institution', models.CharField(max_length=255, verbose_name='Nombre de la institución')),
                ('font_primary', models.CharField(max_length=255, verbose_name='Fuente primaria')),
                ('font_secondary', models.CharField(max_length=255, verbose_name='Fuente secundaria')),
                ('font_third', models.CharField(max_length=255, verbose_name='Fuente terciaria')),
                ('primary_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='#FFFFFF', image_field=None, max_length=10, samples=None, verbose_name='Color primario')),
                ('secondary_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='#FFFFFF', image_field=None, max_length=10, samples=None, verbose_name='Color secundario')),
                ('third_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='#FFFFFF', image_field=None, max_length=10, samples=None, verbose_name='Color terciario')),
                ('success_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='#FFFFFF', image_field=None, max_length=10, samples=None, verbose_name='Color de éxito')),
                ('error_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='#FFFFFF', image_field=None, max_length=10, samples=None, verbose_name='Color de error')),
                ('warning_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='#FFFFFF', image_field=None, max_length=10, samples=None, verbose_name='Color de advertencia')),
                ('info_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='#FFFFFF', image_field=None, max_length=10, samples=None, verbose_name='Color de información')),
                ('is_activated', models.BooleanField(default=True, verbose_name='Activado')),
            ],
            options={
                'verbose_name': 'Interfaz',
                'verbose_name_plural': 'Interfaz',
                'db_table': 'interface',
            },
        ),
    ]
