# Generated by Django 5.1.5 on 2025-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0007_interfaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='orientation',
            field=models.FloatField(default=0.0, help_text='Orientación del aula en grados (0-360), en la entrada principal de la universidad la orientaciones 120. ', verbose_name='Orientación'),
        ),
    ]
